### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by Techtony96** [ajpappas/Discord.java#58]
```
[ERROR] Unhandled exception caught dispatching event PresenceUpdateEvent
java.lang.NullPointerException: null
        at net.ajpappas.discord.modules.gametracker.GameLog.addGame(GameLog.java:109)
        at net.ajpappas.discord.modules.gametracker.GameLog.addGameLog(GameLog.java:42)
        at net.ajpappas.discord.modules.gametracker.GameListener.onGameChange(GameListener.java:30)
        at sx.blah.discord.api.events.EventDispatcher$MethodEventHandler.handle(EventDispatcher.java:723)
        at sx.blah.discord.api.events.EventDispatcher.lambda$null$19(EventDispatcher.java:653)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by Techtony96** [comment]
Maybe fixed in 9a42ba050fe98f09845433c0405cdea0777f6376
